### ISSUE TITLE
I wanna fly bug 

### ISSUE THREAD

**Issue by MOOOOs** [cepheidqq/FactorySkyline#18]
Switch can't be toggled off no matter i i toggle it off it shows it toggled off but i can still fly.

**Comment by cepheidqq** [comment]
fixed in 0.0.9

**Comment by K14Morg** [comment]
> Switch can't be toggled off no matter i i toggle it off it shows it toggled off but i can still fly.

The flight does not turn off while you are flying. First you have to land on the ground by double pressing the space bar. Then turn off the flight in the mod's settings.

**Comment by MOOOOs** [comment]
> > Switch can't be toggled off no matter i i toggle it off it shows it toggled off but i can still fly.
> 
> The flight does not turn off while you are flying. First you have to land on the ground by double pressing the space bar. Then turn off the flight in the mod's settings.

You think i didn't tried that before posting this issue? Why you freeposting with useless solution. Btw mod author fixed that in 0.0.9
