### ISSUE TITLE
No way to close/hide the menu once it is called

### ISSUE THREAD

**Issue by nclow** [cepheidqq/FactorySkyline#26]
Once you press 'R' to call the menu, is there no way to hide it again? I've tried 0.0.7 on EA and 0.0.9 on Experimental so I could see the custom input system you wrote, and maybe I'm missing it, but I can't find a way to dismiss the menu. It would be nice if it wasn't taking up space when it's not being used.

Pretty psyched to see where this mod is headed too. Nice job.

**Comment by cepheidqq** [comment]
Use Esc Key in the current version. It could be solved after merging the version of EA and Experimantal, it can add a new key to hide the mod UI without calling the game menu.

**Comment by nclow** [comment]
Ok if I press Esc to bring up the game menu and then Esc to dismiss it again, the Factory Skyline menu disappears, so I guess that's working as intended. Thanks. This mod is wonderful and it'll really help me building out my megafactory.
