### ISSUE TITLE
Blueprints are not saved after restarting the game

### ISSUE THREAD

**Issue by K14Mua** [cepheidqq/FactorySkyline#5]
Everything is clear from the name. In mod, you can create blueprints, rename them and group them by folders. But this is pointless, since after restarting the game everything is deleted.

**Comment by cepheidqq** [comment]
The Blueprints design is too big to store in the configure file, and it bind with the buildings in game.
So it saved in the saving file of the game, make sure to save your game before restart and have not switch on the "Do not save anything" option.
If it still clear what you do, let me know.
